[package]
name = "photo"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
egui_extras = { version = "0.31.1", features = ["default", "all_loaders"] }
image = { version = "0.25.6", features = ["jpeg", "png"] }
rfd = "0.15.3"
url = "2.5.4"
